### PR TITLE
el8 support

### PR DESCRIPTION
**Pull request by markVnl**
NethServer/dev#6152

### CODE REVIEW

**Comment by gsanchietti** [comment]
While we add the `releasever` variable, we can't change the requirements for python-requests otherwise the package will not work on NethServer 7 (while it should still work on Fedora).

If you want, I can open a `el8` branch, but as I reported back to community, I'm not sure the work on mock will continue for NS 8.

**Comment by markVnl** [comment]
> 
> 
> While we add the `releasever` variable, we can't change the requirements for python-requests otherwise the package will not work on NethServer 7 (while it should still work on Fedora).

I will retest it; 
mock from epel-7 actually pulls in python3-requests, so it should be even possible to drop the requirement in nethserver-mock. 
I will test it on a vanilla centos-7 installation again.


EDIT:
also note we  need python3-requests, AFAIK it's a unnoticed imperfection because mock pulls in the python 3 implementation. see:
https://github.com/NethServer/nethserver-mock/blob/master/src/bin/issue-refs#L1

**Comment by markVnl** [comment]
Diging in to it further i'm inclined to state it firmer: It is a bug fix :)

On a vanilla centos-7 **without epel** you get the python2 based mock version 1.2.17-1, which pulls in (python2)  python-requests.  In this scenario nethsever-mock should pull in python3-requests. 

**With epel** the "bug" stays unnoticed because you pull in the python**3** based mock version 1.4.19-1, which (as stated) pulls in  python3-requests.

If you wish a can change the title to reflect these new insights (just kidding..)

**Comment by gsanchietti** [comment]
After further review, and quick test, I agree with you: the fix works and should not introduce any regressions.

I'm going to merge it. Do you think we need also to release it on updates?

**Review by gsanchietti — APPROVED** [review]

**Comment by markVnl** [comment]
> . Do you think we need also to release it on updates?

Now it is in the pipe the release can wait.

Thank you for reconsidering!

**Pull request merged**
